name: lab03

on:
  push:
    paths:
      - "hw/lab03/**"
      - ".github/workflows/lab03.yml"
  pull_request:
    paths:
      - "hw/lab03/**"
      - ".github/workflows/lab03.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - "01_pipes_pingpong"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make python3

      - name: Build ${{ matrix.task }}
        working-directory: hw/lab03/${{ matrix.task }}
        run: make

      - name: Test ${{ matrix.task }}
        working-directory: hw/lab03/${{ matrix.task }}
        run: make test